### PR TITLE
WCARAV-3: add explicit provider for PKCS12 keystore type

### PR DESCRIPTION
**Pull request by philipp-t**
* check if PKCS12 is set as keystone type and initialize the keystore with SunJSSE provider
* no configuration option to change provider for PKCS12
* no provider added for JKS and other keystore types, because it should not be needed

### CODE REVIEW

**Comment by stefanseifert** [comment]
i thought it should work without such a special provider - do you have a documentation link why this is required here? i suppose we have to make this configurable and not hard-code the condition.
also we need to add a unit test - can you provide a sample PKS12 file we can add for the unit tests?

note: we already have a unit tests with a .p12 file https://github.com/wcm-io-caravan/caravan-commons/blob/develop/httpclient/src/test/java/io/wcm/caravan/commons/httpclient/impl/helpers/CertificateLoaderTest.java

**Comment by philipp-t** [comment]
Ok, I create a Test with a pfx cert file. I also add a configuration field for the provider, but this is a non backward compatible change isn't it?

**Comment by stefanseifert** [comment]
you mean the HttpClientConfig interface? we've java 8, so this is not a problem. just use default methods.

**Comment by philipp-t** [comment]
But the OSGi Config gets a new Configuration Property. If I add a default method the Baseline analysis breaks the build with the required version increase error :(

**Comment by stefanseifert** [comment]
when adding the default method we have to increase the version - but only to the next 1.x version which is backwards compatible, and not the the next 2.x version which breaks everything.

**Pull request merged**
